#!/usr/bin/env python3
"""Stage 4 — enrich docs/ontology-data.json(.js) with the term-intelligence layer.

Adds, non-destructively:
  * `plainDescription` on every term (from descriptions.json)
  * a top-level `termMatches` block (the proposed, human-gated matches)
  * per-term `similarTerms` (curie + relation + confidence) for UI panels

Run AFTER build-ontology-map.py (it consumes the generator's output and adds a
layer on top). Idempotent. Rewrites ontology-data.json and ontology-data.js.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
ONT_JSON = ROOT / "docs" / "ontology-data.json"
ONT_JS = ROOT / "docs" / "ontology-data.js"
DESC = HERE / "descriptions.json"
MATCHES = HERE / "term-matches.json"


def main() -> int:
    data = json.loads(ONT_JSON.read_text())
    desc = json.loads(DESC.read_text())
    matchdoc = json.loads(MATCHES.read_text())
    proposals = matchdoc.get("proposals", [])

    # 1. plainDescription per term
    covered = 0
    for t in data["terms"]:
        pd = desc.get(t["curie"])
        if pd:
            t["plainDescription"] = pd
            covered += 1

    # 1b. mirror plainDescription onto graph nodes (used by the schema-map popup)
    for n in data.get("graph", {}).get("nodes", []):
        pd = desc.get(n.get("curie") or n.get("id"))
        if pd:
            n["plainDescription"] = pd

    # 2. per-term similarTerms (bidirectional)
    sim: dict[str, list] = {}
    for m in proposals:
        for src, dst in ((m["a"], m["b"]), (m["b"], m["a"])):
            sim.setdefault(src, []).append({
                "curie": dst, "relation": m["relation"],
                "confidence": m.get("confidence"),
                "canonical": m.get("canonical"),
            })
    for t in data["terms"]:
        if t["curie"] in sim:
            t["similarTerms"] = sim[t["curie"]]

    # 3. top-level block
    data["termMatches"] = {
        "status": matchdoc.get("status", "proposed"),
        "count": len(proposals),
        "proposals": proposals,
    }
    data.setdefault("stats", {})["plain_descriptions"] = covered
    data["stats"]["term_matches"] = len(proposals)

    ONT_JSON.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    ONT_JS.write_text(
        "// Auto-generated by build-ontology-map.py — do not edit.\n"
        "window.COMET_ONTOLOGY = " + json.dumps(data, ensure_ascii=False) + ";\n"
    )
    print(f"enriched: {covered}/{len(data['terms'])} terms got plainDescription; "
          f"{len(proposals)} match proposals; wrote ontology-data.json + .js")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
